language: java
script: mvn clean package -P test -DskipTests=true
after_success:
  - mvn clean test jacoco:report coveralls:report
branches:
  only:
  - master
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
os: linux
