language: java
branches:
  only:
  - master
script: mvn clean package -P test -DskipTests=true
after_success:
  - mvn clean test -P test jacoco:report coveralls:report
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
os: linux
