language: java
branches:
  only:
  - master
install:
  - mvn test-compile -P test -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -P test jacoco:report
after_success:
  - mvn coveralls:report
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
os: linux
