DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
	id BIGINT NOT NULL,
	name VARCHAR(128) NOT NULL,
	age INT(11) NOT NULL,
	PRIMARY KEY(id)
);

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
	id BIGINT NOT NULL,
	state VARCHAR(64) NOT NULL,
	city VARCHAR(128) NOT NULL,
	zipcode VARCHAR(8),
	street_address VARCHAR(256) NOT NULL,
	PRIMARY KEY(id)
);