DELETE FROM PERSON;
INSERT INTO PERSON VALUES(1, 'Maria Santos', 44);
INSERT INTO PERSON VALUES(2, 'Jose Carlos', 20);
INSERT INTO PERSON VALUES(3, 'Antonio Santos', 23);
INSERT INTO PERSON VALUES(4, 'Marcos Rocha', 20);
INSERT INTO PERSON VALUES(5, 'Jose Paulo', 16);

DELETE FROM ADDRESS;
INSERT INTO ADDRESS VALUES(1, 'SP', 'Sao Paulo', '02200123', 'rua central');	